### ISSUE TITLE
Violation of foreign key constraints on OBJECTCLASS

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/plugin-ade-manager#1]
When registering an ADE into the database, it can happen that a child object is written to `OBJECTCLASS` prior to its parent object. This violates the foreign key constraint on `SUPERCLASS_ID` and thus causes an exception.

**Comment by yaozhihang** [comment]
OK, thanks.  I'll look into this problem and fix it soon.

**Comment by yaozhihang** [comment]
fixed in b494e74d862f90a3f67f26fa805e8f4ee0042c4e
