### ISSUE TITLE
Cannot Transformation

### ISSUE THREAD

**Issue by ufalakbar** [3dcitydb/plugin-ade-manager#15]
Sorry, i try to transform TestADE XSD file but when I click a "Transform" button in ADE Manager, the transformation process in console is not run but stuck like in the picture?
![image](https://user-images.githubusercontent.com/71371278/172096620-c39c2c7a-9c46-4b57-94cc-975dfc10957e.png)

**Comment by yaozhihang** [comment]
It is a known issue. The ADE manager has trouble with java >= 17. Please use a lower java version e.g. java 11. This should solve the issue.

**Comment by ufalakbar** [comment]
it's works, previously i use java 17 and then I change it with java 14. Thank you
