### ISSUE TITLE
Only Last Node of the first Level of ADE is imported/shown in List

### ISSUE THREAD

**Issue by e3DChristoph** [3dcitydb/plugin-ade-manager#17]
Hey,

![192250512-9c09f5ad-89a1-40da-af60-cd480554b715](https://user-images.githubusercontent.com/23355799/196691121-85733b9f-2846-4ed4-bd09-c8517422a7ce.png)

As seen in the picture, when importing the EnergyADE 1.0 from KIT, only the Weatherstation is available after the import, while there should be more Nodes to see.

Maybe this should be an Issue for the Importer/Exporter and not the ADE Extension. If so please let me know so I can move it.

Thanks

**Comment by clausnagel** [comment]
Only top-level features are shown here. So, it's correct. The other features defined in the ADE are rather meant to be used as children of other features (e.g., of a `Building`).
