### ISSUE TITLE
BUG: ADE Manager won't drop ADE del_* functions upon ADE removal

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/plugin-ade-manager#19]
Hi!

I am using the 3DCityDB Suite 2023.0.1.
Starting from an XSD file, I generate the DDL scripts that I can then use to register the ADE (only the database part, no Java libraries yet). Installation works perfectly (tables, functions, etc. are generated correctly).

BUT:
When I choose "Remove ADE", the process runs and completes, but the additional ADE del_* functions are not dropped. In my case, using "t1" as ADE prefix, all del_t1_...(...) functions remain.
All the rest, including the ADE env_t1_...(...) functions, is correctly dropped.

I have created a mini "Test 1 ADE" to reproduce the bug. Here it is:
[Test1_ADE.zip](https://github.com/user-attachments/files/15898602/Test1_ADE.zip)

**Comment by clausnagel** [comment]
Thanks for reporting. Fixed with 0c62e02a3e551ebecb69c5bd29c3c52c1b4b7bc3. The fix will be included in the next release.
