### ISSUE TITLE
Table names in DDL scripts versus tablename in objectclass

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/plugin-ade-manager#2]
The generated DDL scripts use camelCase style for table names. But both Oracle and PostgreSQL are not case-sensitive unless you use double quotes (which is not recommended by anyone). Oracle turns table names into UPPER case, Postgres uses lower case.

The camelCase style is also imported into the `objectclass` table, which might create some problems as it is not aligned with the actual table names. Table names should be lower case both in the scripts and the `objectclass` table. For Oracle we might choose to use upper case. (Btw, is there an easy way to use underscores like in other tables of the 3DCityDB? ;)

**Comment by clausnagel** [comment]
Agree that we should use lower case table names.

**Comment by yaozhihang** [comment]
thanks, i'll fix it soon.

**Comment by yaozhihang** [comment]
fxied in 229ffa67ca8676e43835cd3896e265f566b8ab61
