### ISSUE TITLE
how to register ADE through the impexp-cli

### ISSUE THREAD

**Issue by expeditionengineer** [3dcitydb/plugin-ade-manager#20]
Hello,

I would like to use the ADE-Manager-Plugin on the impexp-cli to register a ADE in a 3DcityDB instance automatically without the use of the GUI application. Is that generally possible? I couldnt find documentation on that topic. 
Thanks in advance,
Tobias

**Comment by yaozhihang** [comment]
Hi Tobias,
it is unfortunately not possible to run the ADE-Manager-Plugin via command line interface. You have to use the GUI to register your ADE. 
Zhihang
