### ISSUE TITLE
Limit available digits in ADE prefix text field

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/plugin-ade-manager#3]
I was curious if I could also use a looong prefix for an ADE and if it appears in the DDL scripts ;)
Turns out the tool only allows 4 characters. This is good. But, maybe the textfield in the GUI should have the same behaviour to not surprise users. Btw, I haven't tested with numbers or special characters, yet ;)

**Comment by yaozhihang** [comment]
Thanks for the tests. Yes, we need some more hints for users when they interact with the GUI . I'll improve this soon.

**Comment by yaozhihang** [comment]
Improved in https://github.com/3dcitydb/plugin-ade-manager/commit/ab00ca8dfaf5d7a0d09a0429e6729d772141fbef

**Comment by yaozhihang** [comment]
OK, fixed. see https://github.com/3dcitydb/plugin-ade-manager/commit/d72f63b85fba87c97b0ff78287685c7eb387181b
